baseurl = "/"
languageCode = "en"
title = "Padbury Clock"
theme = "vex"

[params]
  description = "A basic digital clock screensaver from Australian American designer Robert Padbury that displays the current time in an elegant and legible font, in either a 12 or a 24 hour format."

  # Put your custom stylesheets and scripts
  custom_stylesheets = []
  custom_scripts = []

  # Additional meta
  [[params.meta]]
    name = "Padbury Clock"
    description = "A basic digital clock screensaver from Australian American designer Robert Padbury that displays the current time in an elegant and legible font, in either a 12 or a 24 hour format."

  # Navigation bar informations
  [params.navbar]
    logo = "Padbury Clock"

  # Header
  [params.header]
    title = "Padbury Clock by Robert Padbury"
    text = "An homage to Padbury Clock: A basic digital clock screensaver from Australian American designer Robert Padbury."
    [params.header.image]
      path = "images/padbury-clock-screen-saver.png"
      alt = "Padbury Clock Screensaver"
    [params.header.button]
      link = "/padbury-clock.zip"
      text = "Download "

  [params.promo]
    title = "Minimal screensaver for Mac"
    text = "The Padbury Clock Screensaver is a minimalist's dream – and should be the default on every computer. You can choose between 12 hour and 24 hour format in an elegant and legible font, and nothing more. It's simple, clean, give it a try on your machine. ✨"
    [params.promo.image]
      path = "images/padbury-clock-daniel-padbury.jpg"
      alt = "Padbury Clock Screensaver"

  [params.feature_list]
    title = "Thank you, Robert Padbury, wherever you are."
    [[params.feature_list.items]]
      image = ""
      title = "Released in 2014"
      text = 'Padbury Clock allowed users to, "Transform your Mac into an elegant minimalist clock with this Screen Saver." But, a few years ago, it disappeared off the web. I am bringing it back from the dead (with no support or guarantees).'
      button_link = "/padbury-clock.zip"
      button_text = "Download "
    [[params.feature_list.items]]
      image = ""
      title = "Found on Product Hunt"
      text = "Padbury Clock Screensaver, made by Robert Padbury, debuted on Product Hunt on 2015-03-26. It quickly rose to #3 Product of the Day. Rightfully so; Padbury Clock has been one of my favorite screensavers of all time since that day."
      button_link = "https://www.producthunt.com/posts/padbury-clock-screensaver"
      button_text = "See it on Product Hunt"
    [[params.feature_list.items]]
      image = ""
      title = "Hi!"
      text = "I'm Chris Short. Apple macOS user, DevOps practioner, and all around nerd. I'm tired of sharing this with friends and then weeks later someone else coming to ask me for a copy of it."
      button_link = "https://chrisshort.net/"
      button_text = "About Chris Short"

  # Footer uses navbar data